<a href="https://colab.research.google.com/github/MdShahadatHossainbd/ML/blob/master/4_Save_Model_Using_Joblib_And_Pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:

model.coef_

array([135.78767123])

In [ ]:
model.intercept_

180616.43835616432

In [ ]:
model.predict([[5000]])

array([859554.79452055])

In [ ]:
import pickle

In [ ]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [ ]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [ ]:
mp.coef_

array([135.78767123])

In [ ]:
mp.intercept_

180616.43835616432

In [ ]:
mp.predict([[5000]])

array([859554.79452055])

In [ ]:
from sklearn.externals import joblib

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [ ]:
mj = joblib.load('model_joblib')

In [ ]:
mj.coef_

array([135.78767123])

In [ ]:
mj.intercept_

180616.43835616432

In [ ]:


mj.predict([[5000]])