<a href="https://colab.research.google.com/github/MdShahadatHossainbd/ML/blob/master/Linear_Regression_with_Multiple_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
df = pd.read_csv('car-data.csv')

In [ ]:
df

speed  age  exp  risk
0    200   23  7.0    75
1    220   21  6.5    95
2    180   25  6.0    80
3    150   18  NaN    90
4    175   19  6.6    85
5    160   20  7.5    70
6    180   21  6.5    85
7    165   25  6.3    84
8    155   27  6.1    82

In [ ]:
df.exp

0    7.0
1    6.5
2    6.0
3    NaN
4    6.6
5    7.5
6    6.5
7    6.3
8    6.1
Name: exp, dtype: float64

In [15]:
df.exp.mean()

6.5625

In [19]:
exp_fit = df.exp.median()
exp_fit

6.5

In [20]:
df.exp = df.exp.fillna(exp_fit)

In [21]:
df

speed  age  exp  risk
0    200   23  7.0    75
1    220   21  6.5    95
2    180   25  6.0    80
3    150   18  6.5    90
4    175   19  6.6    85
5    160   20  7.5    70
6    180   21  6.5    85
7    165   25  6.3    84
8    155   27  6.1    82

In [ ]:
df.risk

0    75
1    95
2    80
3    90
4    85
5    70
6    85
7    84
8    82
Name: risk, dtype: int64

In [ ]:
df.age

0    23
1    21
2    25
3    18
4    19
5    20
6    21
7    25
8    27
Name: age, dtype: int64

In [22]:
reg = linear_model.LinearRegression()

In [26]:
reg.fit(df[['speed','age','exp']],df.risk)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
reg.predict([[160,13,5]])

array([121.27585689])

In [28]:
reg.predict([[160,33,5]])

array([86.10188221])

In [29]:
reg.coef_

array([  0.10279984,  -1.75869873, -15.44109945])

In [30]:
reg.intercept_

204.8964636194854